### ISSUE TITLE
Highlight for Float Win does not work correctly

### ISSUE THREAD

**Issue by phongnh** [PhilRunninger/bufselect#28]
Hi,

When I open BufSelect, highlight for Float Win does not work correctly:

<img width="1624" alt="image" src="https://github.com/PhilRunninger/bufselect/assets/438791/aa9faf3a-6045-4206-99d4-9a939f9f8c90">

It should be:

<img width="698" alt="image" src="https://github.com/PhilRunninger/bufselect/assets/438791/a8f280e7-56ac-4e8f-8656-8bdedd134a3b">

When I toggle Help section, it also does not work as well:

<img width="690" alt="image" src="https://github.com/PhilRunninger/bufselect/assets/438791/3a212345-f38a-4ff1-82ff-6e0d8542c2a8">

**Comment by PhilRunninger** [comment]
I don't see this happening on my setup. My guess is that your colorscheme is not defining the **NormalFloat** highlight group, or is doing so in a way you dislike. What does the statement `:hi NormalFloat` return?  You can override or create the highlight group yourself by putting this statement in your **init.vim**, after setting your colorscheme: `hi! link NormalFloat Normal`

**Comment by phongnh** [comment]
> I don't see this happening on my setup. My guess is that your colorscheme is not defining the **NormalFloat** highlight group, or is doing so in a way you dislike. What does the statement `:hi NormalFloat` return? You can override or create the highlight group yourself by putting this statement in your **init.vim**, after setting your colorscheme: `hi! link NormalFloat Normal`

Thank you. You're right, the colorscheme that I am using (https://github.com/ishan9299/nvim-solarized-lua) has not defined `NormalFloat` yet.

Before I close the issue do you think that it does make senses to add option to allow to overwrite highlight groups in float window, like this PR https://github.com/PhilRunninger/bufselect/pull/29 but its value is empty by default?

**Comment by phongnh** [comment]
Sorry for making you confused. There are two problem in this issue:

1. BufSelect - Sort Highlight is not working correctly on startup - this pr https://github.com/PhilRunninger/bufselect/pull/30 to try to address this problem by adding `redraw!` on `CursorMoved` event.

<img width="606" alt="image" src="https://github.com/PhilRunninger/bufselect/assets/438791/b21b0f09-8601-4458-8725-317d44a0b84c">

2. Float Window's background is not the same as normal buffer - the reason maybe that `NormalFloat` is not defined in colorscheme. This PR https://github.com/PhilRunninger/bufselect/pull/29 to add option to allow to update float win's highlight

**Comment by PhilRunninger** [comment]
I'd rather not add complexity to this plugin to address a deficiency in the colorscheme, so I will close #29. Like I demonstrated above, the workaround is to define **NormalFloat** in your `init.vim` or `init.lua`.

---

I'm not sure what's happening with the sort highlight. I see it flicker as you show it in your screenshots briefly, but it always resolves to the intended appearance. However, if I remove this line - https://github.com/PhilRunninger/bufselect/blob/master/autoload/bufselect.vim#L12, the flickering goes away, and everything still ends up as it should. I'm not a fan of adding the `redraw` as you have it in #30. What happens when you remove the one on line 12 instead?

I added that `redraw!` in this commit 23c7a6136fdecf1fa8fcbcf25e3e3320cfc8cfef, but I don't remember the actual circumstances, so it might be OK to remove it if that solves your issue.

**Comment by phongnh** [comment]
> I'd rather not add complexity to this plugin to address a deficiency in the colorscheme, so I will close #29. Like I demonstrated above, the workaround is to define **NormalFloat** in your `init.vim` or `init.lua`.
> 
> I'm not sure what's happening with the sort highlight. I see it flicker as you show it in your screenshots briefly, but it always resolves to the intended appearance. However, if I remove this line - https://github.com/PhilRunninger/bufselect/blob/master/autoload/bufselect.vim#L12, the flickering goes away, and everything still ends up as it should. I'm not a fan of adding the `redraw` as you have it in #30. What happens when you remove the one on line 12 instead?
> 
> I added that `redraw!` in this commit [23c7a61](https://github.com/PhilRunninger/bufselect/commit/23c7a6136fdecf1fa8fcbcf25e3e3320cfc8cfef), but I don't remember the actual circumstances, so it might be OK to remove it if that solves your issue.

I tried to remove `redraw!` line (https://github.com/PhilRunninger/bufselect/blob/master/autoload/bufselect.vim#L12) as you told, it solved my issue.

**Comment by phongnh** [comment]
> I'd rather not add complexity to this plugin to address a deficiency in the colorscheme, so I will close #29. Like I demonstrated above, the workaround is to define **NormalFloat** in your `init.vim` or `init.lua`.
> 

Just adding a note about PR #29, It is not only for workaround but it will allow to customize/link BufSelect* highlight groups based on current colorscheme. For example, something like this:

```vim
let g:BufSelectFloatWinHighlight = 'NormalFloat:Normal,BufSelectSort:Pmenu,BufSelectCurrent:Keyword'
```

Thanks.

**Comment by PhilRunninger** [comment]
I've been thinking about changing the way the settings are done. I would like to combine them all into a single dictionary, like are used in the newer lua plugins. Perhaps I'll work your `WinHighlight` feature into that. In the meantime, the customization described at the bottom of the README should be capable of doing the overrides you describe.

**Comment by phongnh** [comment]
Yes, sounds good. Closing PR now. Thanks for your support.
